AllCops:
  TargetRubyVersion: 2.6

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Style/RescueStandardError:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Naming/AccessorMethodName:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
